name: CI

on:
  push:
    branches: [main]

jobs:
  integrationTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm start &
      - run: npx newman run tests/integration-foundsresearchsources.json
      - run: npx newman run tests/integration-greenhousegasemissions-stats.json
      - run: npx newman run tests/integration-renewablepowercapacities-stats.json
      
      
