name: Running Code Coverage

on: [push, pull_request]


jobs:
  
  build:

    runs-on: ubuntu-latest
   

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 6
        

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build 
    - name: Strat application
      run: npm start &
    # - name: Backend Tests
    #   run: npx newman run tests/integration-foundsresearchsources-stats.json

    - name: Run the tests
      run: npm test --coverage
      

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
       